// Local Gut backend lifecycle for the Electron app.
//
// Owns a docker-compose stack under <userData>/local: generates secrets,
// renders litellm.yaml from the provider keys the user supplies, pulls the
// prebuilt gut-desktop image from GHCR and waits for it to come up.
// Runtime install: macOS prefers Colima (free, no license limits) via brew;
// otherwise we point the user at Docker Desktop.
const { app, shell } = require('electron');
const { spawn } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const http = require('http');
const path = require('path');

const GHCR = 'ghcr.io/valteryde/gut-desktop';
const PROVIDER_KEYS = [
  'ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'GEMINI_API_KEY',
  'DEEPSEEK_API_KEY', 'OPENROUTER_API_KEY',
];

const stackDir = () => path.join(app.getPath('userData'), 'local');
const envPath = () => path.join(stackDir(), '.env');
const composePath = () => path.join(stackDir(), 'compose.yaml');
const litellmPath = () => path.join(stackDir(), 'litellm.yaml');

const imageTag = () =>
  process.env.GUT_DESKTOP_IMAGE ||
  `${GHCR}:${app.isPackaged ? app.getVersion() : 'latest'}`;

// GUI apps get a bare PATH — brew/docker/colima live in /opt/homebrew or
// /usr/local on every Mac we care about.
const EXTRA_PATH = ['/opt/homebrew/bin', '/usr/local/bin', '/usr/bin', '/bin'];
const SPAWN_ENV = {
  ...process.env,
  PATH: [...(process.env.PATH || '').split(path.delimiter), ...EXTRA_PATH]
    .filter(Boolean).join(path.delimiter),
};

function run(cmd, args, onLine) {
  return new Promise((resolve) => {
    const p = spawn(cmd, args, { shell: false, env: SPAWN_ENV });
    let out = '';
    const data = (d) => {
      out += d;
      if (onLine) onLine(String(d).replace(/\n$/, ''));
    };
    p.stdout.on('data', data);
    p.stderr.on('data', data);
    p.on('error', () => resolve({ code: -1, out }));
    p.on('close', (code) => resolve({ code, out }));
  });
}

function which(bin) {
  return SPAWN_ENV.PATH.split(path.delimiter)
    .find((d) => fs.existsSync(path.join(d, bin)));
}

// ── .env ────────────────────────────────────────────────────────────────
const rand = (n) => crypto.randomBytes(n).toString('base64url').slice(0, n);

function readEnv() {
  const env = {};
  try {
    for (const line of fs.readFileSync(envPath(), 'utf8').split('\n')) {
      const m = line.match(/^([A-Z_]+)=(.*)$/);
      if (m) env[m[1]] = m[2];
    }
  } catch (_) { /* no env yet */ }
  return env;
}

function writeEnv(env) {
  const lines = [
    '# Generated by the Gut app — edit via Settings → Local desktop.',
    `LITELLM_MASTER_KEY=${env.LITELLM_MASTER_KEY}`,
    `POSTGRES_PASSWORD=${env.POSTGRES_PASSWORD}`,
    `VNC_PASSWORD=${env.VNC_PASSWORD}`,
    `GUT_API_TOKEN=${env.GUT_API_TOKEN}`,
    `DEFAULT_MODEL=${env.DEFAULT_MODEL}`,
    'RESOLUTION=1024x768',
    'UI_SCALE=1.0',
    '',
    ...PROVIDER_KEYS.map((k) => `${k}=${env[k] || ''}`),
  ];
  fs.writeFileSync(envPath(), lines.join('\n') + '\n', { mode: 0o600 });
}

function keysSet() {
  const env = readEnv();
  return Object.fromEntries(PROVIDER_KEYS.map((k) => [k, !!env[k]]));
}

// ── litellm.yaml rendered from whichever provider keys are set ──────────
const MODELS = {
  ANTHROPIC_API_KEY: [
    ['claude-sonnet-4-5', 'anthropic/claude-sonnet-4-5-20250929'],
    ['claude-haiku-4-5', 'anthropic/claude-haiku-4-5-20251001'],
  ],
  OPENAI_API_KEY: [
    ['gpt-5', 'openai/gpt-5'],
    ['gpt-4o', 'openai/gpt-4o'],
  ],
  GEMINI_API_KEY: [
    ['gemini-2.5-pro', 'gemini/gemini-2.5-pro'],
    ['gemini-2.5-flash', 'gemini/gemini-2.5-flash'],
  ],
  OPENROUTER_API_KEY: [
    ['openrouter/claude-sonnet-4.5', 'openrouter/anthropic/claude-sonnet-4.5'],
    ['openrouter/gpt-5', 'openrouter/openai/gpt-5'],
    ['openrouter/qwen3-vl', 'openrouter/qwen/qwen3-vl-235b-a22b-instruct'],
  ],
  DEEPSEEK_API_KEY: [
    ['deepseek-chat', 'deepseek/deepseek-chat'],
  ],
};

function writeLitellmConfig(env) {
  const entries = [];
  for (const key of PROVIDER_KEYS) {
    if (!env[key]) continue;
    for (const [name, model] of MODELS[key] || []) {
      entries.push(
        `  - model_name: ${name}\n` +
        `    litellm_params:\n` +
        `      model: ${model}\n` +
        `      api_key: os.environ/${key}\n` +
        `      max_tokens: 8192`);
    }
  }
  const yaml =
    '# Generated by the Gut app from your provider keys.\n' +
    'general_settings:\n' +
    '  master_key: os.environ/LITELLM_MASTER_KEY\n' +
    '  database_url: os.environ/DATABASE_URL\n' +
    'litellm_settings:\n' +
    '  store_prompts_in_spend_logs: false\n' +
    '  request_timeout: 600\n' +
    'model_list:\n' +
    (entries.length ? entries.join('\n') + '\n' : '  []\n');
  fs.writeFileSync(litellmPath(), yaml);
  return entries.length > 0;
}

function writeCompose() {
  fs.writeFileSync(composePath(), `name: gut-local

# Generated by the Gut app — the same stack as docker-compose.yml, but
# pulling prebuilt images instead of building from source.
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: litellm
    volumes:
      - gut-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm -d litellm"]
      interval: 5s
      timeout: 5s
      retries: 20

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    restart: unless-stopped
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    volumes:
      - ./litellm.yaml:/app/config.yaml:ro
    env_file: .env
    environment:
      DATABASE_URL: postgresql://litellm:\${POSTGRES_PASSWORD}@db:5432/litellm
      LITELLM_MASTER_KEY: \${LITELLM_MASTER_KEY}
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \\"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:4000/health/liveliness').status==200 else 1)\\""]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 60s

  desktop:
    image: ${imageTag()}
    restart: unless-stopped
    shm_size: 2gb
    env_file: .env
    environment:
      DISPLAY: ":0"
      VNC_PASSWORD: \${VNC_PASSWORD}
      GUT_API_TOKEN: \${GUT_API_TOKEN}
      LITELLM_URL: http://litellm:4000
      LITELLM_MASTER_KEY: \${LITELLM_MASTER_KEY}
      DEFAULT_MODEL: \${DEFAULT_MODEL}
      DEVICE_NAME: local
    ports:
      - "127.0.0.1:6080:6080"
      - "127.0.0.1:8000:8000"
    volumes:
      - gut-chrome:/home/agent/.gut-chrome
      - gut-home:/home/agent
    depends_on:
      litellm:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/api/version || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

volumes:
  gut-pgdata:
  gut-chrome:
  gut-home:
`);
}

const composeArgs = () =>
  ['compose', '-p', 'gut-local', '-f', composePath(), '--env-file', envPath()];

function probeAgent() {
  return new Promise((resolve) => {
    const req = http.get(
      { host: '127.0.0.1', port: 8000, path: '/api/version', timeout: 3000 },
      (res) => resolve(res.statusCode === 200));
    req.on('error', () => resolve(false));
    req.on('timeout', () => { req.destroy(); resolve(false); });
  });
}

// ── public API ──────────────────────────────────────────────────────────

async function status() {
  const docker = (await run('docker', ['info'])).code === 0;
  return {
    runtime: docker ? 'ready' : 'missing',
    stack: docker && (await probeAgent()) ? 'running' : 'stopped',
    image: imageTag(),
    dir: stackDir(),
  };
}

const INSTALL_URLS = {
  darwin: 'https://docs.docker.com/desktop/setup/install/mac-install/',
  win32: 'https://docs.docker.com/desktop/setup/install/windows-install/',
  linux: 'https://docs.docker.com/engine/install/',
};

async function installRuntime(log) {
  const brewDir = which('brew');
  if (process.platform === 'darwin' && brewDir) {
    const brew = path.join(brewDir, 'brew');
    log('Installing Colima + Docker CLI via Homebrew…');
    let r = await run(brew, ['install', 'colima', 'docker', 'docker-compose'], log);
    if (r.code !== 0) return { ok: false, error: 'brew install failed' };
    log('Starting Colima VM…');
    r = await run('colima', ['start', '--cpu', '4', '--memory', '8', '--disk', '60'], log);
    if (r.code !== 0) return { ok: false, error: 'colima start failed' };
    return { ok: (await run('docker', ['info'])).code === 0 };
  }
  // No brew (mac), or Windows/Linux: Docker Desktop / Engine is a manual
  // install — open the docs and let the user re-check.
  shell.openExternal(INSTALL_URLS[process.platform] || INSTALL_URLS.linux);
  return { ok: false, needsManual: true };
}

async function start(keys, log) {
  fs.mkdirSync(stackDir(), { recursive: true });
  const env = readEnv();
  for (const k of PROVIDER_KEYS) {
    if (keys[k] && String(keys[k]).trim()) env[k] = String(keys[k]).trim();
  }
  if (!PROVIDER_KEYS.some((k) => env[k])) {
    return { ok: false, error: 'no model provider key set' };
  }
  if (!env.VNC_PASSWORD) {
    env.VNC_PASSWORD = rand(24);
    env.GUT_API_TOKEN = env.VNC_PASSWORD;
    env.LITELLM_MASTER_KEY = `sk-${rand(48)}`;
    env.POSTGRES_PASSWORD = rand(24);
  }
  if (!writeLitellmConfig(env)) {
    return { ok: false, error: 'no models configured' };
  }
  if (!env.DEFAULT_MODEL) {
    env.DEFAULT_MODEL = litellmConfigFirstModel(env);
  }
  writeEnv(env);
  writeCompose();

  log(`Pulling and starting the stack (image ${imageTag()}) — first run downloads several GB…`);
  const r = await run('docker', [...composeArgs(), 'up', '-d', '--wait'], log);
  if (r.code !== 0) return { ok: false, error: 'docker compose up failed' };
  return { ok: true, host: '127.0.0.1', password: env.VNC_PASSWORD };
}

function litellmConfigFirstModel(env) {
  for (const key of PROVIDER_KEYS) {
    if (env[key] && MODELS[key]) return MODELS[key][0][0];
  }
  return 'claude-sonnet-4-5';
}

async function stop() {
  const r = await run('docker', [...composeArgs(), 'down']);
  return { ok: r.code === 0 };
}

module.exports = { status, installRuntime, start, stop, keysSet };
