// Local Gut backend lifecycle for the Electron app.
//
// Packaged builds own a docker-compose stack under <userData>/local:
// generates secrets, renders litellm.yaml from the provider keys the user
// supplies, pulls the prebuilt gut-desktop image from GHCR and waits for
// it to come up. In dev (`electron .` — unpackaged) the "local backend"
// is instead the repo's own docker-compose.yml (project `gut`): the stack
// a developer runs with `docker compose up` while working on the daemon.
// Runtime install: macOS prefers Colima (free, no license limits) via brew;
// otherwise we point the user at Docker Desktop.
const { app, shell } = require('electron');
const { spawn } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const http = require('http');
const path = require('path');

const GHCR = 'ghcr.io/valteryde/gut-desktop';
const PROVIDER_KEYS = [
  'ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'GEMINI_API_KEY',
  'DEEPSEEK_API_KEY', 'OPENROUTER_API_KEY',
];

const DEV = !app.isPackaged;
const repoDir = path.resolve(__dirname, '..');

// Two compose projects can be "the local backend": the repo's dev stack
// (`gut`, built from source — what `docker compose up` runs) and the one
// the app generates under userData (`gut-local`, prebuilt GHCR image).
// Config/key writes go to MANAGED; lifecycle commands hit whichever
// project owns the desktop container — see desktopContainer().
const MANAGED = DEV ? 'gut' : 'gut-local';

const stackDir = () => path.join(app.getPath('userData'), 'local');
const composeFile = (proj = MANAGED) => proj === 'gut'
  ? path.join(repoDir, 'docker-compose.yml')
  : path.join(stackDir(), 'compose.yaml');
const envFile = (proj = MANAGED) => proj === 'gut'
  ? path.join(repoDir, '.env')
  : path.join(stackDir(), '.env');
const envPath = () => envFile();
const composePath = () => composeFile();
const litellmPath = () => path.join(stackDir(), 'litellm.yaml');

const imageTag = () =>
  process.env.GUT_DESKTOP_IMAGE ||
  `${GHCR}:${app.isPackaged ? app.getVersion() : 'latest'}`;

// GUI apps get a bare PATH — brew/docker/colima live in /opt/homebrew or
// /usr/local on every Mac we care about.
const EXTRA_PATH = ['/opt/homebrew/bin', '/usr/local/bin', '/usr/bin', '/bin'];
const SPAWN_ENV = {
  ...process.env,
  PATH: [...(process.env.PATH || '').split(path.delimiter), ...EXTRA_PATH]
    .filter(Boolean).join(path.delimiter),
};

function run(cmd, args, onLine) {
  return new Promise((resolve) => {
    const p = spawn(cmd, args, { shell: false, env: SPAWN_ENV });
    let out = '';
    const data = (d) => {
      out += d;
      if (onLine) onLine(String(d).replace(/\n$/, ''));
    };
    p.stdout.on('data', data);
    p.stderr.on('data', data);
    p.on('error', () => resolve({ code: -1, out }));
    p.on('close', (code) => resolve({ code, out }));
  });
}

// docker compose floods progress lines; the real failure is almost always
// the last non-empty line of output.
const fail = (what, r) => {
  const tail = String(r.out).split('\n').map((l) => l.trim())
    .filter(Boolean).pop();
  return { ok: false, error: tail ? `${what}: ${tail}` : what };
};

function which(bin) {
  return SPAWN_ENV.PATH.split(path.delimiter)
    .find((d) => fs.existsSync(path.join(d, bin)));
}

// ── .env ────────────────────────────────────────────────────────────────
const rand = (n) => crypto.randomBytes(n).toString('base64url').slice(0, n);

function readEnv() {
  const env = {};
  try {
    for (const line of fs.readFileSync(envPath(), 'utf8').split('\n')) {
      const m = line.match(/^([A-Z_]+)=(.*)$/);
      if (m) env[m[1]] = m[2];
    }
  } catch (_) { /* no env yet */ }
  return env;
}

function writeEnv(env) {
  const lines = [
    '# Generated by the Gut app — edit via Settings → Provider keys.',
    `LITELLM_MASTER_KEY=${env.LITELLM_MASTER_KEY}`,
    `POSTGRES_PASSWORD=${env.POSTGRES_PASSWORD}`,
    `VNC_PASSWORD=${env.VNC_PASSWORD}`,
    `GUT_API_TOKEN=${env.GUT_API_TOKEN}`,
    `DEFAULT_MODEL=${env.DEFAULT_MODEL}`,
    'RESOLUTION=1024x768',
    'UI_SCALE=1.0',
    '',
    ...PROVIDER_KEYS.map((k) => `${k}=${env[k] || ''}`),
  ];
  fs.writeFileSync(envPath(), lines.join('\n') + '\n', { mode: 0o600 });
}

function keysSet() {
  const env = readEnv();
  return Object.fromEntries(PROVIDER_KEYS.map((k) => [k, !!env[k]]));
}

// Non-destructive .env write: update only the given KEY=VALUE lines and
// keep everything else (comments, secrets, port overrides) untouched.
// Used for the dev repo's .env, which is hand-maintained.
function mergeEnv(updates) {
  let lines = [];
  try { lines = fs.readFileSync(envPath(), 'utf8').split('\n'); }
  catch (_) { /* no env yet */ }
  const seen = new Set();
  const out = lines.map((l) => {
    const m = l.match(/^([A-Z_]+)=/);
    if (m && m[1] in updates) {
      seen.add(m[1]);
      return `${m[1]}=${updates[m[1]]}`;
    }
    return l;
  });
  for (const [k, v] of Object.entries(updates)) {
    if (!seen.has(k)) out.push(`${k}=${v}`);
  }
  fs.writeFileSync(envPath(), out.join('\n').replace(/\n*$/, '\n'),
    { mode: 0o600 });
}

// Merge provider-key edits into .env without starting the stack; an empty
// string removes the key. Once the stack has been provisioned the env file
// also carries its secrets — keep those intact and re-render the litellm
// model list so the change applies on the next `up`. Before first start
// the file holds provider lines only; start() fills in the rest.
function saveKeys(keys) {
  const updates = {};
  for (const k of PROVIDER_KEYS) {
    if (k in keys) updates[k] = String(keys[k] || '').trim();
  }
  if (DEV) {
    mergeEnv(updates);
    return keysSet();
  }
  fs.mkdirSync(stackDir(), { recursive: true });
  const env = readEnv();
  Object.assign(env, updates);
  if (env.VNC_PASSWORD) {
    writeEnv(env);
    writeLitellmConfig(env);
  } else {
    const lines = [
      '# Provider keys saved from Settings — the app fills in the rest on first start.',
      ...PROVIDER_KEYS.map((k) => `${k}=${env[k] || ''}`),
    ];
    fs.writeFileSync(envPath(), lines.join('\n') + '\n', { mode: 0o600 });
  }
  return keysSet();
}

// ── litellm.yaml rendered from whichever provider keys are set ──────────
const MODELS = {
  ANTHROPIC_API_KEY: [
    ['claude-sonnet-4-5', 'anthropic/claude-sonnet-4-5-20250929'],
    ['claude-haiku-4-5', 'anthropic/claude-haiku-4-5-20251001'],
  ],
  OPENAI_API_KEY: [
    ['gpt-5', 'openai/gpt-5'],
    ['gpt-4o', 'openai/gpt-4o'],
  ],
  GEMINI_API_KEY: [
    ['gemini-2.5-pro', 'gemini/gemini-2.5-pro'],
    ['gemini-2.5-flash', 'gemini/gemini-2.5-flash'],
  ],
  OPENROUTER_API_KEY: [
    ['openrouter/claude-sonnet-4.5', 'openrouter/anthropic/claude-sonnet-4.5'],
    ['openrouter/gpt-5', 'openrouter/openai/gpt-5'],
    ['openrouter/qwen3-vl', 'openrouter/qwen/qwen3-vl-235b-a22b-instruct'],
  ],
  DEEPSEEK_API_KEY: [
    ['deepseek-chat', 'deepseek/deepseek-chat'],
  ],
};

function writeLitellmConfig(env) {
  const entries = [];
  for (const key of PROVIDER_KEYS) {
    if (!env[key]) continue;
    for (const [name, model] of MODELS[key] || []) {
      entries.push(
        `  - model_name: ${name}\n` +
        `    litellm_params:\n` +
        `      model: ${model}\n` +
        `      api_key: os.environ/${key}\n` +
        `      max_tokens: 8192`);
    }
  }
  const yaml =
    '# Generated by the Gut app from your provider keys.\n' +
    'general_settings:\n' +
    '  master_key: os.environ/LITELLM_MASTER_KEY\n' +
    '  database_url: os.environ/DATABASE_URL\n' +
    '  store_model_in_db: true\n' +
    'litellm_settings:\n' +
    '  store_prompts_in_spend_logs: false\n' +
    '  request_timeout: 600\n' +
    'model_list:\n' +
    (entries.length ? entries.join('\n') + '\n' : '  []\n');
  fs.writeFileSync(litellmPath(), yaml);
  return entries.length > 0;
}

function writeCompose() {
  fs.writeFileSync(composePath(), `name: gut-local

# Generated by the Gut app — the same stack as docker-compose.yml, but
# pulling prebuilt images instead of building from source.
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: litellm
    volumes:
      - gut-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm -d litellm"]
      interval: 5s
      timeout: 5s
      retries: 20

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    restart: unless-stopped
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    volumes:
      - ./litellm.yaml:/app/config.yaml:ro
    env_file: .env
    environment:
      DATABASE_URL: postgresql://litellm:\${POSTGRES_PASSWORD}@db:5432/litellm
      LITELLM_MASTER_KEY: \${LITELLM_MASTER_KEY}
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \\"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:4000/health/liveliness').status==200 else 1)\\""]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 60s

  desktop:
    image: ${imageTag()}
    restart: unless-stopped
    shm_size: 2gb
    env_file: .env
    environment:
      DISPLAY: ":0"
      VNC_PASSWORD: \${VNC_PASSWORD}
      GUT_API_TOKEN: \${GUT_API_TOKEN}
      LITELLM_URL: http://litellm:4000
      LITELLM_MASTER_KEY: \${LITELLM_MASTER_KEY}
      DEFAULT_MODEL: \${DEFAULT_MODEL}
      DEVICE_NAME: local
    ports:
      - "127.0.0.1:6080:6080"
      - "127.0.0.1:8000:8000"
    volumes:
      - gut-chrome:/home/agent/.gut-chrome
      - gut-home:/home/agent
    depends_on:
      litellm:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/api/version || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

volumes:
  gut-pgdata:
  gut-chrome:
  gut-home:
`);
}

const composeArgs = (proj = MANAGED) => [
  'compose', '-p', proj, '-f', composeFile(proj),
  // A missing .env must not break ps/restart — `up` reports it anyway.
  ...(fs.existsSync(envFile(proj)) ? ['--env-file', envFile(proj)] : []),
];

// The gut desktop container, whichever compose project owns it — a running
// one wins over created/exited. Lifecycle commands target this project.
async function desktopContainer() {
  const r = await run('docker',
    ['ps', '-a', '--format', '{{.Names}} {{.State}}']);
  let found = null;
  for (const line of r.out.split('\n')) {
    const m = line.match(/^(gut|gut-local)-desktop-\d+ (.*)$/);
    if (!m) continue;
    const c = { project: m[1], running: m[2].trim() === 'running' };
    if (c.running) return c;
    found = found || c;
  }
  return found;
}

// Any HTTP answer from :8000 means the agent process is alive — the route
// deliberately doesn't matter, older daemons predate /api/version.
function probeAgent() {
  return new Promise((resolve) => {
    const req = http.get(
      { host: '127.0.0.1', port: 8000, path: '/api/version', timeout: 3000 },
      (res) => { res.resume(); resolve(true); });
    req.on('error', () => resolve(false));
    req.on('timeout', () => { req.destroy(); resolve(false); });
  });
}

// ── public API ──────────────────────────────────────────────────────────

async function status() {
  const docker = (await run('docker', ['info'])).code === 0;
  // Container state decides "running", not the HTTP probe: a wedged or
  // outdated daemon must still show Stop/Restart — that's when they're
  // needed most.
  const c = docker ? await desktopContainer() : null;
  const proj = c?.project || MANAGED;
  return {
    runtime: docker ? 'ready' : 'missing',
    stack: c?.running ? 'running' : 'stopped',
    project: proj,
    agent: c?.running ? await probeAgent() : false,
    image: proj === 'gut' ? 'dev build' : imageTag(),
    dir: proj === 'gut' ? repoDir : stackDir(),
  };
}

const INSTALL_URLS = {
  darwin: 'https://docs.docker.com/desktop/setup/install/mac-install/',
  win32: 'https://docs.docker.com/desktop/setup/install/windows-install/',
  linux: 'https://docs.docker.com/engine/install/',
};

async function installRuntime(log) {
  const brewDir = which('brew');
  if (process.platform === 'darwin' && brewDir) {
    const brew = path.join(brewDir, 'brew');
    log('Installing Colima + Docker CLI via Homebrew…');
    let r = await run(brew, ['install', 'colima', 'docker', 'docker-compose'], log);
    if (r.code !== 0) return fail('brew install failed', r);
    log('Starting Colima VM…');
    r = await run('colima', ['start', '--cpu', '4', '--memory', '8', '--disk', '60'], log);
    if (r.code !== 0) return fail('colima start failed', r);
    return { ok: (await run('docker', ['info'])).code === 0 };
  }
  // No brew (mac), or Windows/Linux: Docker Desktop / Engine is a manual
  // install — open the docs and let the user re-check.
  shell.openExternal(INSTALL_URLS[process.platform] || INSTALL_URLS.linux);
  return { ok: false, needsManual: true };
}

async function start(keys, log) {
  const env = readEnv();
  for (const k of PROVIDER_KEYS) {
    if (keys[k] && String(keys[k]).trim()) env[k] = String(keys[k]).trim();
  }
  if (!PROVIDER_KEYS.some((k) => env[k])) {
    return { ok: false, error: 'no model provider key set' };
  }
  if (DEV) {
    // The repo's compose/litellm config are the source files — persist
    // only the provider keys the user pasted, then bring the stack up.
    // Builds the desktop image from source on first run.
    const provided = {};
    for (const k of PROVIDER_KEYS) {
      if (keys[k] && String(keys[k]).trim()) provided[k] = env[k];
    }
    mergeEnv(provided);
    log('Starting the dev stack (project "gut", repo docker-compose.yml)…');
    const r = await run('docker', [...composeArgs(), 'up', '-d', '--wait'],
      log);
    if (r.code !== 0) return fail('docker compose up failed', r);
    return { ok: true, host: '127.0.0.1', password: env.GUT_PASSWORD || '' };
  }
  fs.mkdirSync(stackDir(), { recursive: true });
  if (!env.VNC_PASSWORD) {
    env.VNC_PASSWORD = rand(24);
    env.GUT_API_TOKEN = env.VNC_PASSWORD;
    env.LITELLM_MASTER_KEY = `sk-${rand(48)}`;
    env.POSTGRES_PASSWORD = rand(24);
  }
  if (!writeLitellmConfig(env)) {
    return { ok: false, error: 'no models configured' };
  }
  if (!env.DEFAULT_MODEL) {
    env.DEFAULT_MODEL = litellmConfigFirstModel(env);
  }
  writeEnv(env);
  writeCompose();

  log(`Pulling and starting the stack (image ${imageTag()}) — first run downloads several GB…`);
  const r = await run('docker', [...composeArgs(), 'up', '-d', '--wait'], log);
  if (r.code !== 0) return fail('docker compose up failed', r);
  return { ok: true, host: '127.0.0.1', password: env.VNC_PASSWORD };
}

function litellmConfigFirstModel(env) {
  for (const key of PROVIDER_KEYS) {
    if (env[key] && MODELS[key]) return MODELS[key][0][0];
  }
  return 'claude-sonnet-4-5';
}

async function stop() {
  const proj = (await desktopContainer())?.project || MANAGED;
  const r = await run('docker', [...composeArgs(proj), 'down']);
  return { ok: r.code === 0 };
}

// Bounce the stack: recreate the containers in place and wait on the
// healthchecks, like start(). Picks up .env/config changes too.
async function restart(log) {
  const proj = (await desktopContainer())?.project || MANAGED;
  if (!fs.existsSync(composeFile(proj))) {
    return { ok: false, error: 'local stack has not been created yet' };
  }
  log(`Restarting the local stack (project ${proj})…`);
  const r = await run('docker',
    [...composeArgs(proj), 'up', '-d', '--wait', '--force-recreate'], log);
  if (r.code !== 0) return fail('docker compose up failed', r);
  return { ok: true };
}

// Pull the desktop image matching this app version and recreate the stack.
// Settings → Devices offers this when the local backend runs an older tag.
async function update(log) {
  if (DEV) {
    return { ok: false, error:
      'the dev stack builds from source — rebuild with `docker compose up -d --build`' };
  }
  if (!fs.existsSync(composePath())) {
    return { ok: false, error: 'local stack has not been created yet' };
  }
  writeCompose();  // refresh the image tag for the current app version
  log(`Updating the local desktop to ${imageTag()}…`);
  let r = await run('docker', [...composeArgs(), 'pull'], log);
  if (r.code !== 0) return fail('docker compose pull failed', r);
  r = await run('docker', [...composeArgs(), 'up', '-d', '--wait'], log);
  if (r.code !== 0) return fail('docker compose up failed', r);
  return { ok: true };
}

module.exports =
  { status, installRuntime, start, stop, restart, update, keysSet,
    saveKeys };
