// Local Gut backend lifecycle for the Electron app.
//
// Packaged builds own a docker-compose stack under <userData>/local:
// generates secrets, renders litellm.yaml from the provider keys the user
// supplies, pulls the prebuilt gut-desktop image from GHCR and waits for
// it to come up. In dev (`electron .` — unpackaged) the "local backend"
// is instead the repo's own docker-compose.yml (project `gut`): the stack
// a developer runs with `docker compose up` while working on the daemon.
// Runtime install: macOS prefers Colima (free, no license limits) via brew;
// otherwise we point the user at Docker Desktop.
const { app, shell } = require('electron');
const { spawn } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const http = require('http');
const path = require('path');

const GHCR = 'ghcr.io/valteryde/gut-desktop';
// The *_BASE entries are server URLs, not secrets — they flow through the
// same push/store path so the daemon can discover the servers' models live.
// OPENAI_COMPAT_API_KEY is optional; most LAN servers accept anything.
const PROVIDER_KEYS = [
  'ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'GEMINI_API_KEY',
  'DEEPSEEK_API_KEY', 'OPENROUTER_API_KEY', 'OLLAMA_API_BASE',
  'OPENAI_COMPAT_BASE', 'OPENAI_COMPAT_API_KEY',
  // Search providers — feed the agent's web_search, no models.
  'TAVILY_API_KEY', 'BRAVE_API_KEY', 'SERPER_API_KEY',
];

const DEV = !app.isPackaged;
const repoDir = path.resolve(__dirname, '..');

// Two compose projects can be "the local backend": the repo's dev stack
// (`gut`, built from source — what `docker compose up` runs) and the one
// the app generates under userData (`gut-local`, prebuilt GHCR image).
// Config/key writes go to MANAGED; lifecycle commands hit whichever
// project owns the desktop container — see desktopContainer().
const MANAGED = DEV ? 'gut' : 'gut-local';

const stackDir = () => path.join(app.getPath('userData'), 'local');
const composeFile = (proj = MANAGED) => proj === 'gut'
  ? path.join(repoDir, 'docker-compose.yml')
  : path.join(stackDir(), 'compose.yaml');
const envFile = (proj = MANAGED) => proj === 'gut'
  ? path.join(repoDir, '.env')
  : path.join(stackDir(), '.env');
const envPath = () => envFile();
const composePath = () => composeFile();
const litellmPath = () => path.join(stackDir(), 'litellm.yaml');

const imageTag = () =>
  process.env.GUT_DESKTOP_IMAGE ||
  `${GHCR}:${app.isPackaged ? app.getVersion() : 'latest'}`;

// GUI apps get a bare PATH — brew/docker/colima live in /opt/homebrew or
// /usr/local on every Mac we care about.
const EXTRA_PATH = ['/opt/homebrew/bin', '/usr/local/bin', '/usr/bin', '/bin'];
const SPAWN_ENV = {
  ...process.env,
  PATH: [...(process.env.PATH || '').split(path.delimiter), ...EXTRA_PATH]
    .filter(Boolean).join(path.delimiter),
};

function run(cmd, args, onLine) {
  return new Promise((resolve) => {
    const p = spawn(cmd, args, { shell: false, env: SPAWN_ENV });
    let out = '';
    const data = (d) => {
      out += d;
      if (onLine) onLine(String(d).replace(/\n$/, ''));
    };
    p.stdout.on('data', data);
    p.stderr.on('data', data);
    p.on('error', () => resolve({ code: -1, out }));
    p.on('close', (code) => resolve({ code, out }));
  });
}

// docker compose floods progress lines; the real failure is almost always
// the last non-empty line of output.
const fail = (what, r) => {
  const tail = String(r.out).split('\n').map((l) => l.trim())
    .filter(Boolean).pop();
  return { ok: false, error: tail ? `${what}: ${tail}` : what };
};

function which(bin) {
  return SPAWN_ENV.PATH.split(path.delimiter)
    .find((d) => fs.existsSync(path.join(d, bin)));
}

// ── .env — bootstrap secrets only ────────────────────────────────────────
// Provider keys live in provider-keys.json here (pending) and on the device
// in provider_keys.json (pushed via POST /api/keys); device settings go to
// device-config.json → POST /api/config. .env never carries keys or config.
const rand = (n) => crypto.randomBytes(n).toString('base64url').slice(0, n);

const keysStorePath = () => path.join(stackDir(), 'provider-keys.json');
const cfgStorePath = () => path.join(stackDir(), 'device-config.json');

function readJson(p) {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
  catch (_) { return {}; }
}

function writeJson(p, obj) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(obj), { mode: 0o600 });
}

function readEnv() {
  const env = {};
  try {
    for (const line of fs.readFileSync(envPath(), 'utf8').split('\n')) {
      const m = line.match(/^([A-Z_]+)=(.*)$/);
      if (m) env[m[1]] = m[2];
    }
  } catch (_) { /* no env yet */ }
  return env;
}

// Secrets only — the compose file interpolates these; provider keys and
// settings are pushed to the running daemon over its API instead.
function writeEnv(env) {
  const lines = [
    '# Generated by the Gut app — bootstrap secrets only. Provider keys and',
    '# settings live on the device (Settings → Provider keys).',
    `LITELLM_MASTER_KEY=${env.LITELLM_MASTER_KEY}`,
    `POSTGRES_PASSWORD=${env.POSTGRES_PASSWORD}`,
    `VNC_PASSWORD=${env.VNC_PASSWORD}`,
    `GUT_API_TOKEN=${env.GUT_API_TOKEN}`,
  ];
  fs.writeFileSync(envPath(), lines.join('\n') + '\n', { mode: 0o600 });
}

const apiToken = (env) => env.GUT_API_TOKEN || env.GUT_PASSWORD || '';

// Talk to the local daemon. Any failure just resolves {ok:false} — callers
// treat it as "device not reachable, keys stay pending until next start".
function requestApi(pathname, method, token, body) {
  return new Promise((resolve) => {
    const data = body ? JSON.stringify(body) : null;
    const req = http.request({
      host: '127.0.0.1', port: 8000, path: pathname, method,
      timeout: 8000,
      headers: {
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        ...(data ? { 'Content-Type': 'application/json',
                     'Content-Length': Buffer.byteLength(data) } : {}),
      },
    }, (res) => {
      let out = '';
      res.on('data', (d) => { out += d; });
      res.on('end', () => {
        let parsed = {};
        try { parsed = JSON.parse(out); } catch (_) { /* not json */ }
        resolve({ ok: res.statusCode < 300, body: parsed });
      });
    });
    req.on('error', () => resolve({ ok: false, body: {} }));
    req.on('timeout', () => { req.destroy(); resolve({ ok: false, body: {} }); });
    if (data) req.write(data);
    req.end();
  });
}

// Which keys the local backend can serve — the device's own report when the
// daemon is up (it also sees env keys), else the pending store plus any
// legacy .env keys awaiting migration.
async function keysSet() {
  const env = readEnv();
  const r = await requestApi('/api/keys', 'GET', apiToken(env));
  if (r.ok) {
    return Object.fromEntries(PROVIDER_KEYS.map(
      (k) => [k, !!r.body[k]?.set]));
  }
  const pending = readJson(keysStorePath());
  return Object.fromEntries(PROVIDER_KEYS.map(
    (k) => [k, !!(pending[k] || env[k])]));
}

// The actual key values — pending store first, .env as the legacy fallback
// for installs that still carry keys there. The app's own key store imports
// these so a key entered once can be pushed to other devices.
function keyValues() {
  const env = readEnv();
  const pending = readJson(keysStorePath());
  return Object.fromEntries(PROVIDER_KEYS
    .map((k) => [k, pending[k] || env[k]])
    .filter(([, v]) => v && String(v).trim()));
}

// Save provider-key edits to the pending store (empty removes) and, when
// the daemon is reachable, push them straight to the device — they land in
// provider_keys.json and apply live with no restart. If the stack isn't up
// the keys wait here and start() pushes them once the daemon answers.
async function saveKeys(keys) {
  const updates = {};
  for (const k of PROVIDER_KEYS) {
    if (k in keys) updates[k] = String(keys[k] || '').trim();
  }
  const pending = readJson(keysStorePath());
  for (const [k, v] of Object.entries(updates)) {
    if (v) pending[k] = v; else delete pending[k];
  }
  writeJson(keysStorePath(), pending);
  if (await probeAgent()) {
    const env = readEnv();
    await requestApi('/api/keys', 'POST', apiToken(env), { keys: updates });
  }
  return keysSet();
}

// ── litellm.yaml — static: the daemon registers each provider's models ──
// into LiteLLM's DB store from the pushed keys, so no model_list here.
// Preferred default model per provider key, for the config push on start.
const MODELS = {
  ANTHROPIC_API_KEY: ['claude-sonnet-4-5'],
  OPENAI_API_KEY: ['gpt-5'],
  GEMINI_API_KEY: ['gemini-2.5-flash'],
  OPENROUTER_API_KEY: ['openrouter/claude-sonnet-4.5'],
  DEEPSEEK_API_KEY: ['deepseek-chat'],
};

function writeLitellmConfig() {
  const yaml =
    '# Generated by the Gut app. Provider keys are pushed to the agent\n' +
    '# daemon, which registers models into LiteLLM\'s DB store.\n' +
    'general_settings:\n' +
    '  master_key: os.environ/LITELLM_MASTER_KEY\n' +
    '  database_url: os.environ/DATABASE_URL\n' +
    '  store_model_in_db: true\n' +
    'litellm_settings:\n' +
    '  store_prompts_in_spend_logs: false\n' +
    '  request_timeout: 600\n' +
    'model_list: []\n';
  fs.writeFileSync(litellmPath(), yaml);
}

function writeCompose() {
  fs.writeFileSync(composePath(), `name: gut-local

# Generated by the Gut app — the same stack as docker-compose.yml, but
# pulling prebuilt images instead of building from source.
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: litellm
    volumes:
      - gut-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm -d litellm"]
      interval: 5s
      timeout: 5s
      retries: 20

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    restart: unless-stopped
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    volumes:
      - ./litellm.yaml:/app/config.yaml:ro
    env_file: .env
    environment:
      DATABASE_URL: postgresql://litellm:\${POSTGRES_PASSWORD}@db:5432/litellm
      LITELLM_MASTER_KEY: \${LITELLM_MASTER_KEY}
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \\"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:4000/health/liveliness').status==200 else 1)\\""]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 60s

  openserp:
    image: karust/openserp:latest
    restart: unless-stopped
    # -a 0.0.0.0: default binds 127.0.0.1, unreachable from other containers.
    # --leakless closes the per-query browser instances it spawns.
    command: ["serve", "-a", "0.0.0.0", "-p", "7070", "--leakless"]

  desktop:
    image: ${imageTag()}
    restart: unless-stopped
    shm_size: 2gb
    env_file: .env
    environment:
      DISPLAY: ":0"
      VNC_PASSWORD: \${VNC_PASSWORD}
      GUT_API_TOKEN: \${GUT_API_TOKEN}
      LITELLM_URL: http://litellm:4000
      LITELLM_MASTER_KEY: \${LITELLM_MASTER_KEY}
      # Boot-time desktop settings as deploy defaults — the device's
      # config.json (POST /api/config) overrides them.
      RESOLUTION: "1024x768"
      UI_SCALE: "1.0"
      DEVICE_NAME: local
      OPENSERP_URL: http://openserp:7070
    ports:
      - "127.0.0.1:6080:6080"
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:6443:6443"
      - "127.0.0.1:8443:8443"
    volumes:
      - gut-chrome:/home/agent/.gut-chrome
      - gut-home:/home/agent
    depends_on:
      litellm:
        condition: service_healthy
      openserp:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/api/version || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

volumes:
  gut-pgdata:
  gut-chrome:
  gut-home:
`);
}

const composeArgs = (proj = MANAGED) => [
  'compose', '-p', proj, '-f', composeFile(proj),
  // A missing .env must not break ps/restart — `up` reports it anyway.
  ...(fs.existsSync(envFile(proj)) ? ['--env-file', envFile(proj)] : []),
];

// The gut desktop container, whichever compose project owns it — a running
// one wins over created/exited. Lifecycle commands target this project.
async function desktopContainer() {
  const r = await run('docker',
    ['ps', '-a', '--format', '{{.Names}} {{.State}}']);
  let found = null;
  for (const line of r.out.split('\n')) {
    const m = line.match(/^(gut|gut-local)-desktop-\d+ (.*)$/);
    if (!m) continue;
    const c = { project: m[1], running: m[2].trim() === 'running' };
    if (c.running) return c;
    found = found || c;
  }
  return found;
}

// Any HTTP answer from :8000 means the agent process is alive — the route
// deliberately doesn't matter, older daemons predate /api/version.
function probeAgent() {
  return new Promise((resolve) => {
    const req = http.get(
      { host: '127.0.0.1', port: 8000, path: '/api/version', timeout: 3000 },
      (res) => { res.resume(); resolve(true); });
    req.on('error', () => resolve(false));
    req.on('timeout', () => { req.destroy(); resolve(false); });
  });
}

// ── public API ──────────────────────────────────────────────────────────

async function status() {
  const docker = (await run('docker', ['info'])).code === 0;
  // Container state decides "running", not the HTTP probe: a wedged or
  // outdated daemon must still show Stop/Restart — that's when they're
  // needed most.
  const c = docker ? await desktopContainer() : null;
  const proj = c?.project || MANAGED;
  return {
    runtime: docker ? 'ready' : 'missing',
    stack: c?.running ? 'running' : 'stopped',
    exists: !!c,   // a stack (running or stopped) exists → offer Remove
    project: proj,
    agent: c?.running ? await probeAgent() : false,
    image: proj === 'gut' ? 'dev build' : imageTag(),
    dir: proj === 'gut' ? repoDir : stackDir(),
  };
}

const INSTALL_URLS = {
  darwin: 'https://docs.docker.com/desktop/setup/install/mac-install/',
  win32: 'https://docs.docker.com/desktop/setup/install/windows-install/',
  linux: 'https://docs.docker.com/engine/install/',
};

async function installRuntime(log) {
  const brewDir = which('brew');
  if (process.platform === 'darwin' && brewDir) {
    const brew = path.join(brewDir, 'brew');
    log('Installing Colima + Docker CLI via Homebrew…');
    let r = await run(brew, ['install', 'colima', 'docker', 'docker-compose'], log);
    if (r.code !== 0) return fail('brew install failed', r);
    log('Starting Colima VM…');
    r = await run('colima', ['start', '--cpu', '4', '--memory', '8', '--disk', '60'], log);
    if (r.code !== 0) return fail('colima start failed', r);
    return { ok: (await run('docker', ['info'])).code === 0 };
  }
  // No brew (mac), or Windows/Linux: Docker Desktop / Engine is a manual
  // install — open the docs and let the user re-check.
  shell.openExternal(INSTALL_URLS[process.platform] || INSTALL_URLS.linux);
  return { ok: false, needsManual: true };
}

// Push pending provider keys and device config to the running daemon.
// Keys land in provider_keys.json on the volume and register into LiteLLM
// live; DEFAULT_MODEL etc. land in config.json. Waits for the daemon to
// answer first — the dev compose has no desktop healthcheck, so `up --wait`
// can return while uvicorn is still booting. Anything still unpushed just
// retries on the next start.
async function pushDeviceConfig(env, log) {
  for (let i = 0; i < 60 && !(await probeAgent()); i++) {
    await new Promise((r) => setTimeout(r, 2000));
  }
  const token = apiToken(env);
  const keys = keyValues();
  if (Object.keys(keys).length) {
    const r = await requestApi('/api/keys', 'POST', token, { keys });
    if (!r.ok) log?.('Provider keys saved but not pushed yet — daemon not ready.');
  }
  const cfg = readJson(cfgStorePath());
  if (!cfg.DEFAULT_MODEL) {
    for (const k of PROVIDER_KEYS) {
      if (keys[k] && MODELS[k]) { cfg.DEFAULT_MODEL = MODELS[k][0]; break; }
    }
    writeJson(cfgStorePath(), cfg);
  }
  if (Object.keys(cfg).length) {
    await requestApi('/api/config', 'POST', token, { config: cfg });
  }
}

// Older installs kept provider keys in .env — lift them into the pending
// store before writeEnv scrubs the file, so they reach the daemon's
// provider_keys.json instead of silently disappearing on upgrade.
function migrateEnvKeys(env, pending) {
  let moved = false;
  for (const k of PROVIDER_KEYS) {
    const v = String(env[k] || '').trim();
    if (v && !pending[k]) { pending[k] = v; moved = true; }
  }
  if (moved) writeJson(keysStorePath(), pending);
  return pending;
}

async function start(keys, log) {
  const env = readEnv();
  // Stash freshly pasted keys in the pending store — the device picks them
  // up via /api/keys once it's answering.
  const pending = readJson(keysStorePath());
  for (const k of PROVIDER_KEYS) {
    if (keys[k] && String(keys[k]).trim()) pending[k] = String(keys[k]).trim();
  }
  migrateEnvKeys(env, pending);
  writeJson(keysStorePath(), pending);
  if (!PROVIDER_KEYS.some((k) => pending[k])) {
    return { ok: false, error: 'no model provider key set' };
  }
  if (DEV) {
    // Dev stack: .env is the dev's own secrets file — keys are pushed to
    // the daemon after it comes up, never written there.
    log('Starting the dev stack (project "gut", repo docker-compose.yml)…');
    const r = await run('docker', [...composeArgs(), 'up', '-d', '--wait'],
      log);
    if (r.code !== 0) return fail('docker compose up failed', r);
    await pushDeviceConfig(env, log);
    return { ok: true, host: '127.0.0.1', password: env.GUT_PASSWORD || '' };
  }
  fs.mkdirSync(stackDir(), { recursive: true });
  if (!env.VNC_PASSWORD) {
    env.VNC_PASSWORD = rand(24);
    env.GUT_API_TOKEN = env.VNC_PASSWORD;
    env.LITELLM_MASTER_KEY = `sk-${rand(48)}`;
    env.POSTGRES_PASSWORD = rand(24);
  }
  writeLitellmConfig();
  writeEnv(env);  // secrets only — keys were lifted into the pending store
  writeCompose();

  log(`Pulling and starting the stack (image ${imageTag()}) — first run downloads several GB…`);
  const r = await run('docker', [...composeArgs(), 'up', '-d', '--wait'], log);
  if (r.code !== 0) return fail('docker compose up failed', r);
  await pushDeviceConfig(env, log);
  return { ok: true, host: '127.0.0.1', password: env.VNC_PASSWORD };
}

async function stop() {
  const proj = (await desktopContainer())?.project || MANAGED;
  const r = await run('docker', [...composeArgs(proj), 'down']);
  return { ok: r.code === 0 };
}

// Full teardown: containers + named volumes + the desktop image, then the
// generated stack dir for the packaged project. Docker itself stays —
// Start recreates everything from scratch.
async function remove(log) {
  const c = await desktopContainer();
  const proj = c?.project || MANAGED;
  if (!c && !fs.existsSync(composeFile(proj))) return { ok: true };
  if (proj === 'gut-local' && !fs.existsSync(composeFile(proj))) {
    // Orphaned containers with a deleted stack dir: regenerate just enough
    // compose file for `down` to target the project.
    fs.mkdirSync(stackDir(), { recursive: true });
    writeCompose();
  }
  log?.(`Removing the local stack (project ${proj})…`);
  const r = await run('docker',
    [...composeArgs(proj), 'down', '-v', '--rmi', 'local'], log);
  if (r.code !== 0) return fail('docker compose down failed', r);
  // `--rmi local` only drops untagged build images — remove every tag of
  // the desktop image too (multi-GB; the other services' images are small
  // and may be shared with other compose projects).
  const repo = proj === 'gut' ? 'gut-desktop' : GHCR;
  const ids = (await run('docker', ['images', '-q', repo])).out
    .trim().split('\n').filter(Boolean);
  for (const id of new Set(ids)) await run('docker', ['rmi', id]);
  if (proj === 'gut-local') {
    fs.rmSync(stackDir(), { recursive: true, force: true });
  }
  return { ok: true };
}

// Bounce the stack: recreate the containers in place and wait on the
// healthchecks, like start(). Picks up .env/config changes too.
async function restart(log) {
  const proj = (await desktopContainer())?.project || MANAGED;
  if (!fs.existsSync(composeFile(proj))) {
    return { ok: false, error: 'local stack has not been created yet' };
  }
  log(`Restarting the local stack (project ${proj})…`);
  const r = await run('docker',
    [...composeArgs(proj), 'up', '-d', '--wait', '--force-recreate'], log);
  if (r.code !== 0) return fail('docker compose up failed', r);
  // Migrate any keys still sitting in .env and push pending ones — covers
  // users whose first action after an app update is Restart, not Start.
  const env = readEnv();
  migrateEnvKeys(env, readJson(keysStorePath()));
  await pushDeviceConfig(env, log);
  return { ok: true };
}

// Pull the desktop image matching this app version and recreate the stack.
// Settings → Devices offers this when the local backend runs an older tag.
async function update(log) {
  if (DEV) {
    return { ok: false, error:
      'the dev stack builds from source — rebuild with `docker compose up -d --build`' };
  }
  if (!fs.existsSync(composePath())) {
    return { ok: false, error: 'local stack has not been created yet' };
  }
  writeCompose();  // refresh the image tag for the current app version
  const env = readEnv();
  migrateEnvKeys(env, readJson(keysStorePath()));
  if (env.VNC_PASSWORD) writeEnv(env);  // scrub legacy keys → secrets only
  log(`Updating the local desktop to ${imageTag()}…`);
  let r = await run('docker', [...composeArgs(), 'pull'], log);
  if (r.code !== 0) return fail('docker compose pull failed', r);
  r = await run('docker', [...composeArgs(), 'up', '-d', '--wait'], log);
  if (r.code !== 0) return fail('docker compose up failed', r);
  await pushDeviceConfig(env, log);
  return { ok: true };
}

module.exports =
  { status, installRuntime, start, stop, restart, update, remove, keysSet,
    keyValues, saveKeys };
